---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Innehåll
- type: directory
  path: content/posts
  label: Inlägg
  create: documents
  match: "**/*"
  templates:
  - inlagg
- type: directory
  path: content/podcast
  label: Podcast
  create: documents
  match: "**/*"
  templates:
  - podcast
- type: directory
  path: content/press
  label: Press
  create: documents
  match: "**/*"
upload_dir: content/images
public_path: "/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
